<?php

namespace Database\Factories;

use App\Models\Item;
use App\Models\Asset;
use App\Models\PropertyAckReceipt;
use Illuminate\Database\Eloquent\Factories\Factory;

class ItemFactory extends Factory
{
    protected $model = Item::class;

    public function definition()
    {
        $quantity = $this->faker->randomFloat(3, 1, 100); // e.g., 12.345
        $unitCost = $this->faker->optional()->randomFloat(2, 10, 10000); // can be null
        $unit = $this->faker->optional()->randomElement(['pcs', 'box', 'set', 'unit', 'lot']);
        $status = $this->faker->numberBetween(0, 2);

        return [
            'par_id'         => PropertyAckReceipt::factory(),
            'asset_id'       => Asset::factory(),
            'property_no_raw'=> $this->faker->regexify('[A-Z0-9]{10}'),
            'item_name'      => $this->faker->words(3, true),
            'description'    => $this->faker->sentence(),
            'quantity'       => $quantity,
            'unit'           => $unit,
            'unit_cost'      => $unitCost,
            // total_amount is automatically generated by DB as a stored column
            'sticker_code'   => $this->faker->regexify('STK-[A-Z0-9]{6}'),
            'warranty_months'=> $this->faker->numberBetween(6, 36),
            'status'         => $status,
        ];
    }
}
